#ifndef MATERIAL_H
#define MATERIAL_H

#include <glad/glad.h>
#include <string>

#include <ape/graphics/renderer.h>

namespace ape {

    class Material {
    public:

        /**
         * Binds the texture ID so that sprites can be rendered using it.
         */
        void bind();

        /**
         * Returns the texture ID generated by OpenGL
         * @return The GLuint texture ID
         */
        GLuint getTextureID();

        /**
         * Loads a texture from a file for use in the material.
         * @param  source The path to the file
         * @return        Whether the operation was successful
         */
        bool loadTexture(const std::string& source);

        /**
         * Gets the renderer instance associated with the material.
         * @return A reference to the Renderer class instance owned by the material.
         */
        Renderer& getRenderer();
    private:
        GLuint textureID;

        Renderer renderer;
    };
}

#endif // MATERIAL_H
