#ifndef MATERIAL_H
#define MATERIAL_H

#include <glad/glad.h>
#include <string>

#include <ape/core/vec2.h>

namespace ape {

    class Texture {
    public:
        Texture(GLuint textureID, Vec2f size);

        /**
         * Binds the texture ID so that sprites can be rendered using it.
         */
        void bind();

        /**
         * Returns the texture ID generated by OpenGL
         * @return The GLuint texture ID
         */
        // NOTE: this may cause confusion with the ID assigned by the
        // texture store which is used in the sprite.
        GLuint getTextureID();

        /**
         * Loads a texture from a file for use in the material.
         * @param  source The path to the file
         * @return        Whether the operation was successful
         */
        bool loadTexture(const std::string& source);

        Vec2f getSize();

        bool renderedThisFrame {false};
    private:
        GLuint textureID;
        Vec2f textureSize;

    };
}

#endif // MATERIAL_H
