#ifndef MATERIAL_H
#define MATERIAL_H

#include <glad/glad.h>
#include <string>

#include <ape/core/vec2.h>

namespace ape {

    class Texture {
    public:
        Texture(GLuint textureID, Vec2i size);

        /**
         * Binds the texture ID so that sprites can be rendered using it.
         */
        void bind();

        /**
         * Returns the texture ID generated by OpenGL
         * @return The GLuint texture ID
         */
        GLuint getTextureID();

        /**
         * Loads a texture from a file for use in the material.
         * @param  source The path to the file
         * @return        Whether the operation was successful
         */
        bool loadTexture(const std::string& source);

        Vec2i getSize();
    private:
        GLuint textureID;
        Vec2i textureSize;

    };
}

#endif // MATERIAL_H
